version: 0.0
os: linux

hooks:
  AfterInstall:
    - location: scripts/before_start_server.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
