version: 0.0
os: linux

files:
  - source: /
    destination: ~/japanese-quiz

file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/before_start_server.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
