"""alter score column and add column

Revision ID: 249c045b5377
Revises: 7a32749906e0
Create Date: 2023-07-10 13:11:55.233830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249c045b5377'
down_revision = '7a32749906e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hiragana', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('katakana', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('katakana', 'user_id')
    op.drop_column('hiragana', 'user_id')
    # ### end Alembic commands ###
