"""first_migration_autogen

Revision ID: 1a575075ae05
Revises: 7aeac4637caa
Create Date: 2021-08-02 15:05:51.605880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a575075ae05'
down_revision = '7aeac4637caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
